using HotelManagement.Domain.Entities;
using Microsoft.EntityFrameworkCore;
namespace HotelManagement.Infrastructure.Persistence;
public class HotelDbContext(DbContextOptions<HotelDbContext> options):DbContext(options) {
 public DbSet<Hotel> Hotels=>Set<Hotel>(); public DbSet<Building> Buildings=>Set<Building>(); public DbSet<PricingLocation> PricingLocations=>Set<PricingLocation>(); public DbSet<Floor> Floors=>Set<Floor>(); public DbSet<RoomType> RoomTypes=>Set<RoomType>(); public DbSet<RoomOperationalStatus> RoomOperationalStatuses=>Set<RoomOperationalStatus>(); public DbSet<Room> Rooms=>Set<Room>(); public DbSet<RoomBlockReason> RoomBlockReasons=>Set<RoomBlockReason>(); public DbSet<RoomBlock> RoomBlocks=>Set<RoomBlock>(); public DbSet<AgeCategory> AgeCategories=>Set<AgeCategory>(); public DbSet<PricingPeriod> PricingPeriods=>Set<PricingPeriod>(); public DbSet<GuestNightPrice> GuestNightPrices=>Set<GuestNightPrice>(); public DbSet<Promotion> Promotions=>Set<Promotion>(); public DbSet<PromotionTier> PromotionTiers=>Set<PromotionTier>(); public DbSet<PromotionRoomType> PromotionRoomTypes=>Set<PromotionRoomType>(); public DbSet<PromotionAgeCategory> PromotionAgeCategories=>Set<PromotionAgeCategory>(); public DbSet<ReservationStatus> ReservationStatuses=>Set<ReservationStatus>(); public DbSet<Reservation> Reservations=>Set<Reservation>(); public DbSet<ReservationRoom> ReservationRooms=>Set<ReservationRoom>(); public DbSet<Customer> Customers=>Set<Customer>(); public DbSet<ReservationGuest> ReservationGuests=>Set<ReservationGuest>(); public DbSet<ReservationGuestNightRate> ReservationGuestNightRates=>Set<ReservationGuestNightRate>(); public DbSet<PaymentMethod> PaymentMethods=>Set<PaymentMethod>(); public DbSet<Payment> Payments=>Set<Payment>(); public DbSet<RefundReason> RefundReasons=>Set<RefundReason>(); public DbSet<Refund> Refunds=>Set<Refund>(); public DbSet<ExpenseCategory> ExpenseCategories=>Set<ExpenseCategory>(); public DbSet<Expense> Expenses=>Set<Expense>();
 protected override void OnModelCreating(ModelBuilder b){
  b.Entity<Hotel>().ToTable("hotels").HasKey(x=>x.HotelId); b.Entity<Hotel>().Property(x=>x.HotelId).HasColumnName("hotel_id"); MapHotel(b);
  b.Entity<Building>().ToTable("buildings").HasKey(x=>x.BuildingId); b.Entity<Building>().Property(x=>x.BuildingId).HasColumnName("building_id"); b.Entity<Building>().Property(x=>x.HotelId).HasColumnName("hotel_id"); b.Entity<Building>().Property(x=>x.BuildingCode).HasColumnName("building_code"); b.Entity<Building>().Property(x=>x.BuildingName).HasColumnName("building_name"); Common(b.Entity<Building>());
  b.Entity<PricingLocation>().ToTable("pricing_locations").HasKey(x=>x.PricingLocationId); b.Entity<PricingLocation>().Property(x=>x.PricingLocationId).HasColumnName("pricing_location_id"); b.Entity<PricingLocation>().Property(x=>x.LocationCode).HasColumnName("location_code"); b.Entity<PricingLocation>().Property(x=>x.LocationName).HasColumnName("location_name"); Common(b.Entity<PricingLocation>());
  b.Entity<Floor>().ToTable("floors").HasKey(x=>x.FloorId); Col(b.Entity<Floor>(),x=>x.FloorId,"floor_id"); Col(b.Entity<Floor>(),x=>x.BuildingId,"building_id"); Col(b.Entity<Floor>(),x=>x.PricingLocationId,"pricing_location_id"); Col(b.Entity<Floor>(),x=>x.FloorCode,"floor_code"); Col(b.Entity<Floor>(),x=>x.FloorName,"floor_name"); Col(b.Entity<Floor>(),x=>x.FloorNumber,"floor_number"); Common(b.Entity<Floor>());
  b.Entity<RoomType>().ToTable("room_types").HasKey(x=>x.RoomTypeId); Col(b.Entity<RoomType>(),x=>x.RoomTypeId,"room_type_id"); Col(b.Entity<RoomType>(),x=>x.RoomTypeCode,"room_type_code"); Col(b.Entity<RoomType>(),x=>x.RoomTypeName,"room_type_name"); Col(b.Entity<RoomType>(),x=>x.MaxOccupancy,"max_occupancy"); Col(b.Entity<RoomType>(),x=>x.MaxAdults,"max_adults"); Col(b.Entity<RoomType>(),x=>x.MaxChildren,"max_children"); Common(b.Entity<RoomType>());
  b.Entity<RoomOperationalStatus>().ToTable("room_operational_statuses").HasKey(x=>x.StatusId); Col(b.Entity<RoomOperationalStatus>(),x=>x.StatusId,"status_id"); Col(b.Entity<RoomOperationalStatus>(),x=>x.StatusCode,"status_code"); Col(b.Entity<RoomOperationalStatus>(),x=>x.StatusName,"status_name"); Col(b.Entity<RoomOperationalStatus>(),x=>x.IsSellable,"is_sellable");
  b.Entity<Room>().ToTable("rooms").HasKey(x=>x.RoomId); Col(b.Entity<Room>(),x=>x.RoomId,"room_id"); Col(b.Entity<Room>(),x=>x.FloorId,"floor_id"); Col(b.Entity<Room>(),x=>x.RoomTypeId,"room_type_id"); Col(b.Entity<Room>(),x=>x.OperationalStatusId,"operational_status_id"); Col(b.Entity<Room>(),x=>x.RoomNumber,"room_number"); Common(b.Entity<Room>());
  b.Entity<RoomBlockReason>().ToTable("room_block_reasons").HasKey(x=>x.BlockReasonId); Col(b.Entity<RoomBlockReason>(),x=>x.BlockReasonId,"block_reason_id"); Col(b.Entity<RoomBlockReason>(),x=>x.ReasonCode,"reason_code"); Col(b.Entity<RoomBlockReason>(),x=>x.ReasonName,"reason_name"); Common(b.Entity<RoomBlockReason>());
  b.Entity<RoomBlock>().ToTable("room_blocks").HasKey(x=>x.RoomBlockId); Col(b.Entity<RoomBlock>(),x=>x.RoomBlockId,"room_block_id"); Col(b.Entity<RoomBlock>(),x=>x.RoomId,"room_id"); Col(b.Entity<RoomBlock>(),x=>x.BlockReasonId,"block_reason_id"); Col(b.Entity<RoomBlock>(),x=>x.StartDate,"start_date"); Col(b.Entity<RoomBlock>(),x=>x.EndDate,"end_date"); Col(b.Entity<RoomBlock>(),x=>x.Notes,"notes");
  b.Entity<PricingPeriod>().ToTable("pricing_periods").HasKey(x=>x.PricingPeriodId); Col(b.Entity<PricingPeriod>(),x=>x.PricingPeriodId,"pricing_period_id"); Col(b.Entity<PricingPeriod>(),x=>x.HotelId,"hotel_id"); Col(b.Entity<PricingPeriod>(),x=>x.PeriodCode,"period_code"); Col(b.Entity<PricingPeriod>(),x=>x.PeriodName,"period_name"); Col(b.Entity<PricingPeriod>(),x=>x.StartDate,"start_date"); Col(b.Entity<PricingPeriod>(),x=>x.EndDate,"end_date"); Col(b.Entity<PricingPeriod>(),x=>x.Priority,"priority"); Common(b.Entity<PricingPeriod>());
  b.Entity<GuestNightPrice>().ToTable("guest_night_prices").HasKey(x=>x.GuestNightPriceId); Col(b.Entity<GuestNightPrice>(),x=>x.GuestNightPriceId,"guest_night_price_id"); Col(b.Entity<GuestNightPrice>(),x=>x.PricingPeriodId,"pricing_period_id"); Col(b.Entity<GuestNightPrice>(),x=>x.BuildingId,"building_id"); Col(b.Entity<GuestNightPrice>(),x=>x.PricingLocationId,"pricing_location_id"); Col(b.Entity<GuestNightPrice>(),x=>x.RoomTypeId,"room_type_id"); Col(b.Entity<GuestNightPrice>(),x=>x.AgeCategoryId,"age_category_id"); Col(b.Entity<GuestNightPrice>(),x=>x.RoomId,"room_id"); Col(b.Entity<GuestNightPrice>(),x=>x.PricePerPersonPerNight,"price_per_person_per_night"); Col(b.Entity<GuestNightPrice>(),x=>x.CurrencyCode,"currency_code");
  b.Entity<Promotion>().ToTable("promotions").HasKey(x=>x.PromotionId); Col(b.Entity<Promotion>(),x=>x.PromotionId,"promotion_id"); Col(b.Entity<Promotion>(),x=>x.HotelId,"hotel_id"); Col(b.Entity<Promotion>(),x=>x.PromotionCode,"promotion_code"); Col(b.Entity<Promotion>(),x=>x.PromotionName,"promotion_name"); Col(b.Entity<Promotion>(),x=>x.Description,"description"); Col(b.Entity<Promotion>(),x=>x.ValidFrom,"valid_from"); Col(b.Entity<Promotion>(),x=>x.ValidTo,"valid_to"); Col(b.Entity<Promotion>(),x=>x.DiscountScope,"discount_scope"); Col(b.Entity<Promotion>(),x=>x.Priority,"priority"); Col(b.Entity<Promotion>(),x=>x.CanCombine,"can_combine"); Common(b.Entity<Promotion>());
  b.Entity<PromotionTier>().ToTable("promotion_tiers").HasKey(x=>x.PromotionTierId); Col(b.Entity<PromotionTier>(),x=>x.PromotionTierId,"promotion_tier_id"); Col(b.Entity<PromotionTier>(),x=>x.PromotionId,"promotion_id"); Col(b.Entity<PromotionTier>(),x=>x.MinNights,"min_nights"); Col(b.Entity<PromotionTier>(),x=>x.MaxNights,"max_nights"); Col(b.Entity<PromotionTier>(),x=>x.DiscountType,"discount_type"); Col(b.Entity<PromotionTier>(),x=>x.DiscountValue,"discount_value");
  b.Entity<PromotionRoomType>().ToTable("promotion_room_types").HasKey(x=>new{x.PromotionId,x.RoomTypeId}); Col(b.Entity<PromotionRoomType>(),x=>x.PromotionId,"promotion_id"); Col(b.Entity<PromotionRoomType>(),x=>x.RoomTypeId,"room_type_id");
  b.Entity<PromotionAgeCategory>().ToTable("promotion_age_categories").HasKey(x=>new{x.PromotionId,x.AgeCategoryId}); Col(b.Entity<PromotionAgeCategory>(),x=>x.PromotionId,"promotion_id"); Col(b.Entity<PromotionAgeCategory>(),x=>x.AgeCategoryId,"age_category_id");
  b.Entity<ReservationStatus>().ToTable("reservation_statuses").HasKey(x=>x.StatusId); Col(b.Entity<ReservationStatus>(),x=>x.StatusId,"status_id"); Col(b.Entity<ReservationStatus>(),x=>x.StatusCode,"status_code"); Col(b.Entity<ReservationStatus>(),x=>x.StatusName,"status_name"); Col(b.Entity<ReservationStatus>(),x=>x.BlocksInventory,"blocks_inventory");
  b.Entity<Reservation>().ToTable("reservations").HasKey(x=>x.ReservationId); Col(b.Entity<Reservation>(),x=>x.ReservationId,"reservation_id"); Col(b.Entity<Reservation>(),x=>x.HotelId,"hotel_id"); Col(b.Entity<Reservation>(),x=>x.CustomerId,"customer_id"); Col(b.Entity<Reservation>(),x=>x.StatusId,"status_id"); Col(b.Entity<Reservation>(),x=>x.ReservationNumber,"reservation_number"); Col(b.Entity<Reservation>(),x=>x.CheckInDate,"check_in_date"); Col(b.Entity<Reservation>(),x=>x.CheckOutDate,"check_out_date"); Col(b.Entity<Reservation>(),x=>x.GrossAmount,"gross_amount"); Col(b.Entity<Reservation>(),x=>x.DiscountAmount,"discount_amount"); Col(b.Entity<Reservation>(),x=>x.TaxAmount,"tax_amount"); Col(b.Entity<Reservation>(),x=>x.FinalAmount,"final_amount"); Col(b.Entity<Reservation>(),x=>x.CurrencyCode,"currency_code"); Col(b.Entity<Reservation>(),x=>x.BookingSource,"booking_source"); Col(b.Entity<Reservation>(),x=>x.Notes,"notes");
  b.Entity<ReservationRoom>().ToTable("reservation_rooms").HasKey(x=>x.ReservationRoomId); Col(b.Entity<ReservationRoom>(),x=>x.ReservationRoomId,"reservation_room_id"); Col(b.Entity<ReservationRoom>(),x=>x.ReservationId,"reservation_id"); Col(b.Entity<ReservationRoom>(),x=>x.RoomId,"room_id"); Col(b.Entity<ReservationRoom>(),x=>x.CheckInDate,"check_in_date"); Col(b.Entity<ReservationRoom>(),x=>x.CheckOutDate,"check_out_date"); Col(b.Entity<ReservationRoom>(),x=>x.AdultsCount,"adults_count"); Col(b.Entity<ReservationRoom>(),x=>x.ChildrenCount,"children_count"); Col(b.Entity<ReservationRoom>(),x=>x.GrossAmount,"gross_amount"); Col(b.Entity<ReservationRoom>(),x=>x.DiscountAmount,"discount_amount"); Col(b.Entity<ReservationRoom>(),x=>x.TaxAmount,"tax_amount"); Col(b.Entity<ReservationRoom>(),x=>x.FinalAmount,"final_amount"); Col(b.Entity<ReservationRoom>(),x=>x.AppliedPromotionId,"applied_promotion_id"); Col(b.Entity<ReservationRoom>(),x=>x.AppliedPromotionTierId,"applied_promotion_tier_id");
  b.Entity<Customer>().ToTable("customers").HasKey(x=>x.CustomerId); Col(b.Entity<Customer>(),x=>x.CustomerId,"customer_id"); Col(b.Entity<Customer>(),x=>x.FirstName,"first_name"); Col(b.Entity<Customer>(),x=>x.LastName,"last_name"); Col(b.Entity<Customer>(),x=>x.Phone,"phone"); Col(b.Entity<Customer>(),x=>x.Email,"email"); Col(b.Entity<Customer>(),x=>x.NationalId,"national_id"); Col(b.Entity<Customer>(),x=>x.PassportNumber,"passport_number"); Col(b.Entity<Customer>(),x=>x.Nationality,"nationality"); Col(b.Entity<Customer>(),x=>x.Notes,"notes");
  b.Entity<ReservationGuest>().ToTable("reservation_guests").HasKey(x=>x.ReservationGuestId); Col(b.Entity<ReservationGuest>(),x=>x.ReservationGuestId,"reservation_guest_id"); Col(b.Entity<ReservationGuest>(),x=>x.ReservationRoomId,"reservation_room_id"); Col(b.Entity<ReservationGuest>(),x=>x.FirstName,"first_name"); Col(b.Entity<ReservationGuest>(),x=>x.LastName,"last_name"); Col(b.Entity<ReservationGuest>(),x=>x.DateOfBirth,"date_of_birth"); Col(b.Entity<ReservationGuest>(),x=>x.Nationality,"nationality"); Col(b.Entity<ReservationGuest>(),x=>x.NationalId,"national_id"); Col(b.Entity<ReservationGuest>(),x=>x.PassportNumber,"passport_number"); Col(b.Entity<ReservationGuest>(),x=>x.IsPrimaryGuest,"is_primary_guest");
  b.Entity<ReservationGuestNightRate>().ToTable("reservation_guest_night_rates").HasKey(x=>x.ReservationGuestNightRateId); Col(b.Entity<ReservationGuestNightRate>(),x=>x.ReservationGuestNightRateId,"reservation_guest_night_rate_id"); Col(b.Entity<ReservationGuestNightRate>(),x=>x.ReservationGuestId,"reservation_guest_id"); Col(b.Entity<ReservationGuestNightRate>(),x=>x.StayDate,"stay_date"); Col(b.Entity<ReservationGuestNightRate>(),x=>x.PricingPeriodId,"pricing_period_id"); Col(b.Entity<ReservationGuestNightRate>(),x=>x.AgeCategoryId,"age_category_id"); Col(b.Entity<ReservationGuestNightRate>(),x=>x.AgeAtStay,"age_at_stay"); Col(b.Entity<ReservationGuestNightRate>(),x=>x.OriginalPrice,"original_price"); Col(b.Entity<ReservationGuestNightRate>(),x=>x.DiscountAmount,"discount_amount"); Col(b.Entity<ReservationGuestNightRate>(),x=>x.FinalPrice,"final_price"); Col(b.Entity<ReservationGuestNightRate>(),x=>x.CurrencyCode,"currency_code");
  b.Entity<PaymentMethod>().ToTable("payment_methods").HasKey(x=>x.PaymentMethodId); Col(b.Entity<PaymentMethod>(),x=>x.PaymentMethodId,"payment_method_id"); Col(b.Entity<PaymentMethod>(),x=>x.MethodCode,"method_code"); Col(b.Entity<PaymentMethod>(),x=>x.MethodName,"method_name"); Col(b.Entity<PaymentMethod>(),x=>x.IsActive,"is_active");
  b.Entity<Payment>().ToTable("payments").HasKey(x=>x.PaymentId); Col(b.Entity<Payment>(),x=>x.PaymentId,"payment_id"); Col(b.Entity<Payment>(),x=>x.ReservationId,"reservation_id"); Col(b.Entity<Payment>(),x=>x.PaymentDate,"payment_date"); Col(b.Entity<Payment>(),x=>x.Amount,"amount"); Col(b.Entity<Payment>(),x=>x.PaymentMethodId,"payment_method_id"); Col(b.Entity<Payment>(),x=>x.ReferenceNumber,"reference_number"); Col(b.Entity<Payment>(),x=>x.Status,"status"); Col(b.Entity<Payment>(),x=>x.Notes,"notes");
  b.Entity<RefundReason>().ToTable("refund_reasons").HasKey(x=>x.RefundReasonId); Col(b.Entity<RefundReason>(),x=>x.RefundReasonId,"refund_reason_id"); Col(b.Entity<RefundReason>(),x=>x.ReasonCode,"reason_code"); Col(b.Entity<RefundReason>(),x=>x.ReasonName,"reason_name"); Col(b.Entity<RefundReason>(),x=>x.Description,"description"); Col(b.Entity<RefundReason>(),x=>x.IsActive,"is_active");
  b.Entity<Refund>().ToTable("refunds").HasKey(x=>x.RefundId); Col(b.Entity<Refund>(),x=>x.RefundId,"refund_id"); Col(b.Entity<Refund>(),x=>x.ReservationId,"reservation_id"); Col(b.Entity<Refund>(),x=>x.PaymentId,"payment_id"); Col(b.Entity<Refund>(),x=>x.RefundDate,"refund_date"); Col(b.Entity<Refund>(),x=>x.RefundAmount,"refund_amount"); Col(b.Entity<Refund>(),x=>x.RefundReasonId,"refund_reason_id"); Col(b.Entity<Refund>(),x=>x.RefundMethod,"refund_method"); Col(b.Entity<Refund>(),x=>x.ReferenceNumber,"reference_number"); Col(b.Entity<Refund>(),x=>x.Status,"status");
  b.Entity<ExpenseCategory>().ToTable("expense_categories").HasKey(x=>x.ExpenseCategoryId); Col(b.Entity<ExpenseCategory>(),x=>x.ExpenseCategoryId,"expense_category_id"); Col(b.Entity<ExpenseCategory>(),x=>x.HotelId,"hotel_id"); Col(b.Entity<ExpenseCategory>(),x=>x.CategoryCode,"category_code"); Col(b.Entity<ExpenseCategory>(),x=>x.CategoryName,"category_name"); Col(b.Entity<ExpenseCategory>(),x=>x.IsActive,"is_active");
  b.Entity<Expense>().ToTable("expenses").HasKey(x=>x.ExpenseId); Col(b.Entity<Expense>(),x=>x.ExpenseId,"expense_id"); Col(b.Entity<Expense>(),x=>x.HotelId,"hotel_id"); Col(b.Entity<Expense>(),x=>x.ExpenseCategoryId,"expense_category_id"); Col(b.Entity<Expense>(),x=>x.ExpenseDate,"expense_date"); Col(b.Entity<Expense>(),x=>x.Amount,"amount"); Col(b.Entity<Expense>(),x=>x.Description,"description"); Col(b.Entity<Expense>(),x=>x.SupplierName,"supplier_name"); Col(b.Entity<Expense>(),x=>x.ReferenceNumber,"reference_number"); Col(b.Entity<Expense>(),x=>x.PaymentMethod,"payment_method"); Col(b.Entity<Expense>(),x=>x.Status,"status"); Col(b.Entity<Expense>(),x=>x.CreatedAt,"created_at");
  b.Entity<AgeCategory>().ToTable("age_categories").HasKey(x=>x.AgeCategoryId); Col(b.Entity<AgeCategory>(),x=>x.AgeCategoryId,"age_category_id"); Col(b.Entity<AgeCategory>(),x=>x.HotelId,"hotel_id"); Col(b.Entity<AgeCategory>(),x=>x.CategoryCode,"category_code"); Col(b.Entity<AgeCategory>(),x=>x.CategoryName,"category_name"); Col(b.Entity<AgeCategory>(),x=>x.MinAge,"min_age"); Col(b.Entity<AgeCategory>(),x=>x.MaxAge,"max_age"); Col(b.Entity<AgeCategory>(),x=>x.SortOrder,"sort_order"); Common(b.Entity<AgeCategory>());
 }
 static void MapHotel(ModelBuilder b){var e=b.Entity<Hotel>(); Col(e,x=>x.HotelCode,"hotel_code");Col(e,x=>x.HotelName,"hotel_name");Col(e,x=>x.CurrencyCode,"currency_code");Col(e,x=>x.Timezone,"timezone");Common(e);}
 static void Common<T>(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<T> e) where T:class { foreach(var p in e.Metadata.GetProperties()){ if(p.Name=="IsActive")p.SetColumnName("is_active"); if(p.Name=="Description")p.SetColumnName("description"); if(p.Name=="Notes")p.SetColumnName("notes"); if(p.Name=="Address")p.SetColumnName("address"); if(p.Name=="Phone")p.SetColumnName("phone"); if(p.Name=="Email")p.SetColumnName("email"); }}
 static void Col<T,TProp>(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<T> e,System.Linq.Expressions.Expression<Func<T,TProp>> x,string n) where T:class=>e.Property(x).HasColumnName(n);
}
