-- PHASE 1: Database Tables + Core Constraints
-- Business baseline:
-- 1 reservation -> many reservation_rooms
-- price = guest x night
-- discount tier is evaluated per reservation_room
-- room blocks participate in availability

-- HOTEL / ROOM CONFIGURATION
create table hotels (
 hotel_id bigint generated by default as identity primary key,
 hotel_code varchar(20) not null unique,
 hotel_name varchar(150) not null,
 address text, phone varchar(30), email varchar(150),
 currency_code varchar(3) not null default 'EGP',
 timezone varchar(50) not null default 'Africa/Cairo',
 is_active boolean not null default true,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);

create table buildings (
 building_id bigint generated by default as identity primary key,
 hotel_id bigint not null references hotels(hotel_id),
 building_code varchar(20) not null,
 building_name varchar(100) not null,
 description text, is_active boolean not null default true,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 unique(hotel_id, building_code)
);

create table pricing_locations (
 pricing_location_id bigint generated by default as identity primary key,
 location_code varchar(20) not null unique,
 location_name varchar(100) not null,
 description text, is_active boolean not null default true
);

create table floors (
 floor_id bigint generated by default as identity primary key,
 building_id bigint not null references buildings(building_id),
 pricing_location_id bigint not null references pricing_locations(pricing_location_id),
 floor_code varchar(20) not null, floor_name varchar(100) not null,
 floor_number integer not null, is_active boolean not null default true,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 unique(building_id,floor_code), unique(building_id,floor_number)
);

create table room_types (
 room_type_id bigint generated by default as identity primary key,
 room_type_code varchar(20) not null unique,
 room_type_name varchar(100) not null,
 max_occupancy integer not null check(max_occupancy>0),
 max_adults integer not null check(max_adults>=0),
 max_children integer not null check(max_children>=0),
 description text, is_active boolean not null default true,
 check(max_adults<=max_occupancy), check(max_children<=max_occupancy)
);

create table room_operational_statuses (
 status_id smallint generated by default as identity primary key,
 status_code varchar(30) not null unique,
 status_name varchar(100) not null,
 is_sellable boolean not null default false
);

create table rooms (
 room_id bigint generated by default as identity primary key,
 floor_id bigint not null references floors(floor_id),
 room_type_id bigint not null references room_types(room_type_id),
 operational_status_id smallint not null references room_operational_statuses(status_id),
 room_number varchar(30) not null, description text, notes text,
 is_active boolean not null default true,
 created_at timestamptz not null default now(), created_by uuid,
 updated_at timestamptz not null default now(), updated_by uuid
);

create or replace function enforce_room_number_unique_per_building()
returns trigger language plpgsql as $$
begin
 if exists(
  select 1 from rooms r
  join floors rf on rf.floor_id=r.floor_id
  join floors nf on nf.floor_id=new.floor_id
  where rf.building_id=nf.building_id and r.room_number=new.room_number
    and r.room_id<>coalesce(new.room_id,-1)
 ) then raise exception 'Room number % already exists in this building',new.room_number; end if;
 return new;
end $$;
create trigger trg_rooms_unique_number_per_building
before insert or update of floor_id,room_number on rooms
for each row execute function enforce_room_number_unique_per_building();

create table room_block_reasons (
 block_reason_id bigint generated by default as identity primary key,
 reason_code varchar(30) not null unique, reason_name varchar(100) not null,
 is_active boolean not null default true
);
create table room_blocks (
 room_block_id bigint generated by default as identity primary key,
 room_id bigint not null references rooms(room_id),
 block_reason_id bigint not null references room_block_reasons(block_reason_id),
 start_date date not null, end_date date not null, notes text,
 created_by uuid, created_at timestamptz not null default now(),
 check(end_date>start_date)
);

-- CUSTOMERS / RESERVATIONS
create table customers (
 customer_id bigint generated by default as identity primary key,
 first_name varchar(100) not null,last_name varchar(100) not null,
 phone varchar(30),email varchar(150),national_id varchar(50),passport_number varchar(50),
 nationality varchar(100),notes text,created_at timestamptz not null default now(),
 created_by uuid,updated_at timestamptz not null default now()
);
create table reservation_statuses (
 status_id smallint generated by default as identity primary key,
 status_code varchar(30) not null unique,status_name varchar(100) not null,
 blocks_inventory boolean not null default false
);
create table reservations (
 reservation_id bigint generated by default as identity primary key,
 hotel_id bigint not null references hotels(hotel_id),
 customer_id bigint not null references customers(customer_id),
 status_id smallint not null references reservation_statuses(status_id),
 reservation_number varchar(30) not null unique,
 check_in_date date not null,check_out_date date not null,
 gross_amount numeric(18,2) not null default 0 check(gross_amount>=0),
 discount_amount numeric(18,2) not null default 0 check(discount_amount>=0),
 tax_amount numeric(18,2) not null default 0 check(tax_amount>=0),
 final_amount numeric(18,2) not null default 0 check(final_amount>=0),
 currency_code varchar(3) not null default 'EGP',booking_source varchar(50),notes text,
 created_at timestamptz not null default now(),created_by uuid,
 updated_at timestamptz not null default now(),updated_by uuid,
 check(check_out_date>check_in_date)
);
create table reservation_rooms (
 reservation_room_id bigint generated by default as identity primary key,
 reservation_id bigint not null references reservations(reservation_id) on delete cascade,
 room_id bigint not null references rooms(room_id),
 check_in_date date not null,check_out_date date not null,
 adults_count integer not null default 0 check(adults_count>=0),
 children_count integer not null default 0 check(children_count>=0),
 gross_amount numeric(18,2) not null default 0 check(gross_amount>=0),
 discount_amount numeric(18,2) not null default 0 check(discount_amount>=0),
 tax_amount numeric(18,2) not null default 0 check(tax_amount>=0),
 final_amount numeric(18,2) not null default 0 check(final_amount>=0),
 applied_promotion_id bigint,applied_promotion_tier_id bigint,
 created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
 check(check_out_date>check_in_date),unique(reservation_id,room_id)
);
create table reservation_guests (
 reservation_guest_id bigint generated by default as identity primary key,
 reservation_room_id bigint not null references reservation_rooms(reservation_room_id) on delete cascade,
 first_name varchar(100) not null,last_name varchar(100) not null,date_of_birth date not null,
 nationality varchar(100),national_id varchar(50),passport_number varchar(50),
 is_primary_guest boolean not null default false,created_at timestamptz not null default now()
);

-- PRICING
create table age_categories (
 age_category_id bigint generated by default as identity primary key,
 hotel_id bigint not null references hotels(hotel_id),
 category_code varchar(30) not null,category_name varchar(100) not null,
 min_age integer not null check(min_age>=0),max_age integer,sort_order integer not null default 0,
 is_active boolean not null default true,created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),unique(hotel_id,category_code),
 check(max_age is null or max_age>=min_age)
);
alter table age_categories add constraint ex_age_categories_no_overlap
exclude using gist(hotel_id with =,int4range(min_age,coalesce(max_age+1,2147483647),'[)') with &&)
where(is_active);

create table pricing_periods (
 pricing_period_id bigint generated by default as identity primary key,
 hotel_id bigint not null references hotels(hotel_id),
 period_code varchar(30) not null,period_name varchar(100) not null,
 start_date date not null,end_date date not null,priority integer not null default 0,
 is_active boolean not null default true,created_by uuid,created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),unique(hotel_id,period_code),
 check(end_date>=start_date)
);
create table guest_night_prices (
 guest_night_price_id bigint generated by default as identity primary key,
 pricing_period_id bigint not null references pricing_periods(pricing_period_id),
 building_id bigint not null references buildings(building_id),
 pricing_location_id bigint not null references pricing_locations(pricing_location_id),
 room_type_id bigint not null references room_types(room_type_id),
 age_category_id bigint not null references age_categories(age_category_id),
 price_per_person_per_night numeric(18,2) not null check(price_per_person_per_night>=0),
 currency_code varchar(3) not null default 'EGP',created_by uuid,
 created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
 unique(pricing_period_id,building_id,pricing_location_id,room_type_id,age_category_id)
);

-- PROMOTIONS: discount is per reservation_room
create table promotions (
 promotion_id bigint generated by default as identity primary key,
 hotel_id bigint not null references hotels(hotel_id),
 promotion_code varchar(30) not null,promotion_name varchar(150) not null,description text,
 valid_from date not null,valid_to date not null,discount_scope varchar(30) not null default 'ROOM',
 priority integer not null default 0,can_combine boolean not null default false,
 is_active boolean not null default true,created_by uuid,created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),unique(hotel_id,promotion_code),
 check(valid_to>=valid_from),check(discount_scope='ROOM')
);
create table promotion_tiers (
 promotion_tier_id bigint generated by default as identity primary key,
 promotion_id bigint not null references promotions(promotion_id) on delete cascade,
 min_nights integer not null check(min_nights>=1),max_nights integer,
 discount_type varchar(20) not null check(discount_type in('PERCENTAGE','FIXED_AMOUNT')),
 discount_value numeric(18,2) not null check(discount_value>=0),
 check(max_nights is null or max_nights>=min_nights),
 check(discount_type<>'PERCENTAGE' or discount_value<=100)
);
alter table promotion_tiers add constraint ex_promotion_tiers_no_overlap
exclude using gist(promotion_id with =,int4range(min_nights,coalesce(max_nights+1,2147483647),'[)') with &&);

create table promotion_room_types(
 promotion_id bigint references promotions(promotion_id) on delete cascade,
 room_type_id bigint references room_types(room_type_id),primary key(promotion_id,room_type_id)
);
create table promotion_age_categories(
 promotion_id bigint references promotions(promotion_id) on delete cascade,
 age_category_id bigint references age_categories(age_category_id),primary key(promotion_id,age_category_id)
);
alter table reservation_rooms add foreign key(applied_promotion_id) references promotions(promotion_id);
alter table reservation_rooms add foreign key(applied_promotion_tier_id) references promotion_tiers(promotion_tier_id);

create table reservation_guest_night_rates (
 reservation_guest_night_rate_id bigint generated by default as identity primary key,
 reservation_guest_id bigint not null references reservation_guests(reservation_guest_id) on delete cascade,
 stay_date date not null,pricing_period_id bigint not null references pricing_periods(pricing_period_id),
 age_category_id bigint not null references age_categories(age_category_id),
 age_at_stay integer not null check(age_at_stay>=0),
 original_price numeric(18,2) not null check(original_price>=0),
 discount_amount numeric(18,2) not null default 0 check(discount_amount>=0),
 final_price numeric(18,2) not null check(final_price>=0),
 currency_code varchar(3) not null default 'EGP',created_at timestamptz not null default now(),
 unique(reservation_guest_id,stay_date),
 check(discount_amount<=original_price),check(final_price=original_price-discount_amount)
);

-- FINANCE
create table payment_methods(
 payment_method_id bigint generated by default as identity primary key,
 method_code varchar(30) not null unique,method_name varchar(100) not null,is_active boolean not null default true
);
create table payments(
 payment_id bigint generated by default as identity primary key,
 reservation_id bigint not null references reservations(reservation_id),
 payment_date timestamptz not null default now(),amount numeric(18,2) not null check(amount>0),
 payment_method_id bigint not null references payment_methods(payment_method_id),
 reference_number varchar(100),status varchar(30) not null check(status in('PENDING','SUCCESSFUL','FAILED','REVERSED')),
 notes text,created_by uuid,created_at timestamptz not null default now()
);
create table refund_reasons(
 refund_reason_id bigint generated by default as identity primary key,
 reason_code varchar(30) not null unique,reason_name varchar(100) not null,description text,is_active boolean not null default true
);
create table refunds(
 refund_id bigint generated by default as identity primary key,
 reservation_id bigint not null references reservations(reservation_id),
 payment_id bigint references payments(payment_id),refund_date timestamptz not null default now(),
 refund_amount numeric(18,2) not null check(refund_amount>0),
 refund_reason_id bigint not null references refund_reasons(refund_reason_id),
 refund_method varchar(50),reference_number varchar(100),
 status varchar(30) not null check(status in('PENDING_APPROVAL','APPROVED','REJECTED','PROCESSED')),
 approved_by uuid,created_by uuid,created_at timestamptz not null default now()
);
create table expense_categories(
 expense_category_id bigint generated by default as identity primary key,
 category_code varchar(30) not null unique,category_name varchar(100) not null,is_active boolean not null default true
);
create table expenses(
 expense_id bigint generated by default as identity primary key,
 hotel_id bigint not null references hotels(hotel_id),
 expense_category_id bigint not null references expense_categories(expense_category_id),
 building_id bigint references buildings(building_id),room_id bigint references rooms(room_id),
 expense_date date not null,amount numeric(18,2) not null check(amount>0),
 description text,reference_number varchar(100),created_by uuid,created_at timestamptz not null default now()
);

-- SECURITY / AUDIT
create table app_users(
 user_id uuid primary key,email varchar(150) not null unique,username varchar(100) unique,
 first_name varchar(100),last_name varchar(100),is_active boolean not null default true,
 created_at timestamptz not null default now(),updated_at timestamptz not null default now(),last_login_at timestamptz
);
create table roles(role_id bigint generated by default as identity primary key,role_code varchar(50) not null unique,role_name varchar(100) not null,description text,is_active boolean not null default true);
create table permissions(permission_id bigint generated by default as identity primary key,permission_code varchar(100) not null unique,permission_name varchar(150) not null,module varchar(50) not null,description text);
create table user_roles(user_id uuid references app_users(user_id) on delete cascade,role_id bigint references roles(role_id) on delete cascade,primary key(user_id,role_id));
create table role_permissions(role_id bigint references roles(role_id) on delete cascade,permission_id bigint references permissions(permission_id) on delete cascade,primary key(role_id,permission_id));
create table reservation_status_history(
 history_id bigint generated by default as identity primary key,reservation_id bigint not null references reservations(reservation_id),
 old_status_id smallint references reservation_statuses(status_id),new_status_id smallint not null references reservation_statuses(status_id),
 changed_by uuid,changed_at timestamptz not null default now(),notes text
);
create table audit_logs(
 audit_id bigint generated by default as identity primary key,user_id uuid,
 entity_type varchar(100) not null,entity_id varchar(100) not null,action varchar(30) not null,
 old_values jsonb,new_values jsonb,created_at timestamptz not null default now()
);

-- CORE GUARDS
create or replace function validate_reservation_room_capacity()
returns trigger language plpgsql as $$
declare a int;c int;o int;
begin
 select rt.max_adults,rt.max_children,rt.max_occupancy into a,c,o
 from rooms r join room_types rt on rt.room_type_id=r.room_type_id where r.room_id=new.room_id;
 if new.adults_count>a or new.children_count>c or new.adults_count+new.children_count>o
 then raise exception 'Room capacity exceeded'; end if;
 return new;
end $$;
create trigger trg_validate_capacity before insert or update of room_id,adults_count,children_count
on reservation_rooms for each row execute function validate_reservation_room_capacity();

create or replace function prevent_double_booking()
returns trigger language plpgsql as $$
declare b boolean;
begin
 select rs.blocks_inventory into b from reservations r join reservation_statuses rs on rs.status_id=r.status_id where r.reservation_id=new.reservation_id;
 if coalesce(b,false) and exists(
  select 1 from reservation_rooms rr join reservations r on r.reservation_id=rr.reservation_id
  join reservation_statuses rs on rs.status_id=r.status_id
  where rr.room_id=new.room_id and rr.reservation_room_id<>coalesce(new.reservation_room_id,-1)
  and rs.blocks_inventory and daterange(rr.check_in_date,rr.check_out_date,'[)') && daterange(new.check_in_date,new.check_out_date,'[)')
 ) then raise exception 'Room already reserved for requested dates'; end if;
 if exists(select 1 from room_blocks rb where rb.room_id=new.room_id
  and daterange(rb.start_date,rb.end_date,'[)') && daterange(new.check_in_date,new.check_out_date,'[)'))
 then raise exception 'Room blocked for requested dates'; end if;
 return new;
end $$;
create trigger trg_prevent_double_booking before insert or update of room_id,check_in_date,check_out_date,reservation_id
on reservation_rooms for each row execute function prevent_double_booking();

create or replace function prevent_room_block_conflict()
returns trigger language plpgsql as $$
begin
 if exists(
  select 1 from reservation_rooms rr join reservations r on r.reservation_id=rr.reservation_id
  join reservation_statuses rs on rs.status_id=r.status_id
  where rr.room_id=new.room_id and rs.blocks_inventory
  and daterange(rr.check_in_date,rr.check_out_date,'[)') && daterange(new.start_date,new.end_date,'[)')
 ) then raise exception 'Room block overlaps an active reservation'; end if;
 return new;
end $$;
create trigger trg_prevent_room_block_conflict before insert or update of room_id,start_date,end_date
on room_blocks for each row execute function prevent_room_block_conflict();

create or replace function validate_refund_amount()
returns trigger language plpgsql as $$
declare p numeric(18,2);r numeric(18,2);
begin
 select coalesce(sum(amount),0) into p from payments where reservation_id=new.reservation_id and status='SUCCESSFUL';
 select coalesce(sum(refund_amount),0) into r from refunds where reservation_id=new.reservation_id
 and refund_id<>coalesce(new.refund_id,-1) and status in('APPROVED','PROCESSED');
 if new.status in('APPROVED','PROCESSED') and new.refund_amount>p-r
 then raise exception 'Refund exceeds refundable paid amount'; end if;
 return new;
end $$;
create trigger trg_validate_refund before insert or update of refund_amount,status,reservation_id
on refunds for each row execute function validate_refund_amount();

-- INDEXES
create index ix_room_blocks_room_dates on room_blocks(room_id,start_date,end_date);
create index ix_reservations_customer on reservations(customer_id);
create index ix_reservations_status on reservations(status_id);
create index ix_reservations_dates on reservations(check_in_date,check_out_date);
create index ix_reservation_rooms_room_dates on reservation_rooms(room_id,check_in_date,check_out_date);
create index ix_pricing_periods_dates_priority on pricing_periods(hotel_id,start_date,end_date,priority desc);
create index ix_guest_night_prices_lookup on guest_night_prices(pricing_period_id,building_id,pricing_location_id,room_type_id,age_category_id);
create index ix_payments_reservation_date on payments(reservation_id,payment_date);
create index ix_refunds_reservation_date on refunds(reservation_id,refund_date);
create index ix_expenses_date on expenses(expense_date);

-- SEED LOOKUPS
insert into room_operational_statuses(status_code,status_name,is_sellable) values
('READY','Ready',true),('CLEANING','Cleaning',false),('MAINTENANCE','Maintenance',false),('OUT_OF_SERVICE','Out of Service',false);
insert into reservation_statuses(status_code,status_name,blocks_inventory) values
('PENDING','Pending',false),('CONFIRMED','Confirmed',true),('CHECKED_IN','Checked In',true),('CHECKED_OUT','Checked Out',false),('CANCELLED','Cancelled',false),('NO_SHOW','No Show',false);
insert into room_block_reasons(reason_code,reason_name) values
('MAINTENANCE','Maintenance'),('RENOVATION','Renovation'),('DEEP_CLEANING','Deep Cleaning'),('MANAGEMENT_BLOCK','Management Block'),('OTHER','Other');
insert into payment_methods(method_code,method_name) values
('CASH','Cash'),('CARD','Card'),('BANK_TRANSFER','Bank Transfer'),('ELECTRONIC','Electronic Payment');
insert into refund_reasons(reason_code,reason_name) values
('CANCELLATION','Cancellation'),('EARLY_CHECKOUT','Early Checkout'),('OVERPAYMENT','Overpayment'),('BOOKING_MODIFICATION','Booking Modification'),('SERVICE_ISSUE','Service Issue'),('OTHER','Other');
insert into expense_categories(category_code,category_name) values
('SALARY','Salaries'),('ELECTRICITY','Electricity'),('WATER','Water'),('MAINTENANCE','Maintenance'),('CLEANING','Cleaning'),('LAUNDRY','Laundry'),('SUPPLIES','Supplies'),('MARKETING','Marketing'),('OTHER','Other');
