-- Phase 8 — Expenses + Finance
create table if not exists expense_categories(
  expense_category_id bigint generated by default as identity primary key,
  hotel_id bigint not null references hotels(hotel_id),
  category_code varchar(50) not null,
  category_name varchar(150) not null,
  is_active boolean not null default true,
  unique(hotel_id,category_code)
);

create table if not exists expenses(
  expense_id bigint generated by default as identity primary key,
  hotel_id bigint not null references hotels(hotel_id),
  expense_category_id bigint not null references expense_categories(expense_category_id),
  expense_date date not null,
  amount numeric(18,2) not null check(amount>0),
  description varchar(500),
  supplier_name varchar(200),
  reference_number varchar(100),
  payment_method varchar(50),
  status varchar(30) not null default 'POSTED'
    check(status in('DRAFT','POSTED','VOID')),
  created_at timestamptz not null default now()
);
create index if not exists ix_expenses_hotel_date on expenses(hotel_id,expense_date);
create index if not exists ix_expenses_category_date on expenses(expense_category_id,expense_date);
