namespace HotelManagement.Domain.Entities;

public class Hotel { public long HotelId {get;set;} public string HotelCode {get;set;}=""; public string HotelName {get;set;}=""; public string? Address {get;set;} public string? Phone {get;set;} public string? Email {get;set;} public string CurrencyCode {get;set;}="EGP"; public string Timezone {get;set;}="Africa/Cairo"; public bool IsActive {get;set;}=true; }
public class Building { public long BuildingId {get;set;} public long HotelId {get;set;} public string BuildingCode {get;set;}=""; public string BuildingName {get;set;}=""; public string? Description {get;set;} public bool IsActive {get;set;}=true; }
public class PricingLocation { public long PricingLocationId {get;set;} public string LocationCode {get;set;}=""; public string LocationName {get;set;}=""; public string? Description {get;set;} public bool IsActive {get;set;}=true; }
public class Floor { public long FloorId {get;set;} public long BuildingId {get;set;} public long PricingLocationId {get;set;} public string FloorCode {get;set;}=""; public string FloorName {get;set;}=""; public int FloorNumber {get;set;} public bool IsActive {get;set;}=true; }
public class RoomType { public long RoomTypeId {get;set;} public string RoomTypeCode {get;set;}=""; public string RoomTypeName {get;set;}=""; public int MaxOccupancy {get;set;} public int MaxAdults {get;set;} public int MaxChildren {get;set;} public string? Description {get;set;} public bool IsActive {get;set;}=true; }
public class RoomOperationalStatus { public short StatusId {get;set;} public string StatusCode {get;set;}=""; public string StatusName {get;set;}=""; public bool IsSellable {get;set;} }
public class Room { public long RoomId {get;set;} public long FloorId {get;set;} public long RoomTypeId {get;set;} public short OperationalStatusId {get;set;} public string RoomNumber {get;set;}=""; public string? Description {get;set;} public string? Notes {get;set;} public bool IsActive {get;set;}=true; }
public class RoomBlockReason { public long BlockReasonId {get;set;} public string ReasonCode {get;set;}=""; public string ReasonName {get;set;}=""; public bool IsActive {get;set;}=true; }
public class RoomBlock { public long RoomBlockId {get;set;} public long RoomId {get;set;} public long BlockReasonId {get;set;} public DateOnly StartDate {get;set;} public DateOnly EndDate {get;set;} public string? Notes {get;set;} }
public class AgeCategory { public long AgeCategoryId {get;set;} public long HotelId {get;set;} public string CategoryCode {get;set;}=""; public string CategoryName {get;set;}=""; public int MinAge {get;set;} public int? MaxAge {get;set;} public int SortOrder {get;set;} public bool IsActive {get;set;}=true; }

public class PricingPeriod { public long PricingPeriodId {get;set;} public long HotelId {get;set;} public string PeriodCode {get;set;}="" ; public string PeriodName {get;set;}="" ; public DateOnly StartDate {get;set;} public DateOnly EndDate {get;set;} public int Priority {get;set;} public bool IsActive {get;set;}=true; }
public class GuestNightPrice { public long GuestNightPriceId {get;set;} public long PricingPeriodId {get;set;} public long BuildingId {get;set;} public long PricingLocationId {get;set;} public long RoomTypeId {get;set;} public long AgeCategoryId {get;set;} public long? RoomId {get;set;} public decimal PricePerPersonPerNight {get;set;} public string CurrencyCode {get;set;}="EGP"; }

public class Promotion { public long PromotionId {get;set;} public long HotelId {get;set;} public string PromotionCode {get;set;}=""; public string PromotionName {get;set;}=""; public string? Description {get;set;} public DateOnly ValidFrom {get;set;} public DateOnly ValidTo {get;set;} public string DiscountScope {get;set;}="ROOM"; public int Priority {get;set;} public bool CanCombine {get;set;} public bool IsActive {get;set;}=true; }
public class PromotionTier { public long PromotionTierId {get;set;} public long PromotionId {get;set;} public int MinNights {get;set;} public int? MaxNights {get;set;} public string DiscountType {get;set;}="PERCENTAGE"; public decimal DiscountValue {get;set;} }
public class PromotionRoomType { public long PromotionId {get;set;} public long RoomTypeId {get;set;} }
public class PromotionAgeCategory { public long PromotionId {get;set;} public long AgeCategoryId {get;set;} }

public class ReservationStatus { public short StatusId {get;set;} public string StatusCode {get;set;}=""; public string StatusName {get;set;}=""; public bool BlocksInventory {get;set;} }
public class Reservation { public long ReservationId {get;set;} public long HotelId {get;set;} public long CustomerId {get;set;} public short StatusId {get;set;} public string ReservationNumber {get;set;}=""; public DateOnly CheckInDate {get;set;} public DateOnly CheckOutDate {get;set;} public decimal GrossAmount {get;set;} public decimal DiscountAmount {get;set;} public decimal TaxAmount {get;set;} public decimal FinalAmount {get;set;} public string CurrencyCode {get;set;}="EGP"; public string? BookingSource {get;set;} public string? Notes {get;set;} }
public class ReservationRoom { public long ReservationRoomId {get;set;} public long ReservationId {get;set;} public long RoomId {get;set;} public DateOnly CheckInDate {get;set;} public DateOnly CheckOutDate {get;set;} public int AdultsCount {get;set;} public int ChildrenCount {get;set;} public decimal GrossAmount {get;set;} public decimal DiscountAmount {get;set;} public decimal TaxAmount {get;set;} public decimal FinalAmount {get;set;} public long? AppliedPromotionId {get;set;} public long? AppliedPromotionTierId {get;set;} }

public class Customer { public long CustomerId {get;set;} public string FirstName {get;set;}=""; public string LastName {get;set;}=""; public string? Phone {get;set;} public string? Email {get;set;} public string? NationalId {get;set;} public string? PassportNumber {get;set;} public string? Nationality {get;set;} public string? Notes {get;set;} }
public class ReservationGuest { public long ReservationGuestId {get;set;} public long ReservationRoomId {get;set;} public string FirstName {get;set;}=""; public string LastName {get;set;}=""; public DateOnly DateOfBirth {get;set;} public string? Nationality {get;set;} public string? NationalId {get;set;} public string? PassportNumber {get;set;} public bool IsPrimaryGuest {get;set;} }
public class ReservationGuestNightRate { public long ReservationGuestNightRateId {get;set;} public long ReservationGuestId {get;set;} public DateOnly StayDate {get;set;} public long PricingPeriodId {get;set;} public long AgeCategoryId {get;set;} public int AgeAtStay {get;set;} public decimal OriginalPrice {get;set;} public decimal DiscountAmount {get;set;} public decimal FinalPrice {get;set;} public string CurrencyCode {get;set;}="EGP"; }

public class PaymentMethod { public long PaymentMethodId {get;set;} public string MethodCode {get;set;}=""; public string MethodName {get;set;}=""; public bool IsActive {get;set;}=true; }
public class Payment { public long PaymentId {get;set;} public long ReservationId {get;set;} public DateTimeOffset PaymentDate {get;set;} public decimal Amount {get;set;} public long PaymentMethodId {get;set;} public string? ReferenceNumber {get;set;} public string Status {get;set;}="SUCCESSFUL"; public string? Notes {get;set;} }
public class RefundReason { public long RefundReasonId {get;set;} public string ReasonCode {get;set;}=""; public string ReasonName {get;set;}=""; public string? Description {get;set;} public bool IsActive {get;set;}=true; }
public class Refund { public long RefundId {get;set;} public long ReservationId {get;set;} public long? PaymentId {get;set;} public DateTimeOffset RefundDate {get;set;} public decimal RefundAmount {get;set;} public long RefundReasonId {get;set;} public string? RefundMethod {get;set;} public string? ReferenceNumber {get;set;} public string Status {get;set;}="PENDING_APPROVAL"; }

public class ExpenseCategory { public long ExpenseCategoryId {get;set;} public long HotelId {get;set;} public string CategoryCode {get;set;}=""; public string CategoryName {get;set;}=""; public bool IsActive {get;set;}=true; }
public class Expense { public long ExpenseId {get;set;} public long HotelId {get;set;} public long ExpenseCategoryId {get;set;} public DateOnly ExpenseDate {get;set;} public decimal Amount {get;set;} public string? Description {get;set;} public string? SupplierName {get;set;} public string? ReferenceNumber {get;set;} public string? PaymentMethod {get;set;} public string Status {get;set;}="POSTED"; public DateTimeOffset CreatedAt {get;set;} }
